/*
 * Problem:
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *  By starting with 1 and 2, the first 10 terms will be:
 *
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *  find the sum of the even-valued terms.
 */

#include <stdio.h>

int sum = 0;
int fib_num = 0;
int max = 4000000;

int fib(int n)
{
    if (n <= 1)
        return n;
    return fib(n-1) + fib(n-2);
}

int main()
{
    for (int n = 1; fib_num < max ; n = n + 1)
    {
        printf("%d\n", fib_num = fib(n)); // calculates and prints fibonacci numbers
        if (fib_num % 2 == 0)
            sum = sum + fib_num;
    }
    printf("sum = %d\n", sum);
    return 0;
}
